local configs = require("nvim-treesitter.configs")
require("nvim-treesitter.install").prefer_git = true
configs.setup({
	auto_install = false,
	ensure_installed = {
		"c",
		"lua",
		"vim",
		"vimdoc",
		"query",
		"javascript",
		"tsx",
		"typescript",
		"html",
		"regex",
		"markdown",
		"python",
		"css",
		"markdown_inline",
		"markdown",
		"rst",
		"json",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"json5",
		"csv",
		"comment",
	},
	highlight = {
		enable = true,
	},
	indent = { enable = true },
})
